
version: "3"
services:
  mysql:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=Amresh@#$474
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./api"
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - PORT=5000
      - DB_HOST=2e365f2d1e9d
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Amresh@#$474
      - DB_NAME=blog
      - JWT_ACCESS_SECRET_KEY=euyqwuergwgdh
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app